### PR TITLE
Better resolution on the edges

### PR DESCRIPTION
**Pull request by fullergalway**
Use the properties of the current vector when the target vector is blank.

### CODE REVIEW

**Comment by jgravois** [comment]
thanks for the contribution!

what specific situation does this trap for?  the new codeblock isn't accessed when i load the page and pan and zoom a bit.

**Comment by fullergalway** [comment]
Hi John,

I'm trying windy to model sea surface movement; I found that the visualisation to be missing detail at the waters edge when motion was towards shore. Does this make sense?

Thanks,
Rob.

**Comment by jgravois** [comment]
forgive me if its a dense question, but how can i most easily go about testing the impact of your changes?

**Comment by fullergalway** [comment]
Hi John,

Thanks for this. I followed up by creating a test gfs.json which I expected to trigger the new code block. It did not. I apologise for the inconvenience and am closing this pull request.

Thanks again,
Rob.

**Comment by jgravois** [comment]
> I apologise for the inconvenience and am closing this pull request.

no need to apologise. if you can add an inline code comment as a breadcrumb to explain the effect, i'd be satisfied to merge it.

**Comment by fullergalway** [comment]
As I wasn't able to trigger the block of code using my test data it's probably best to close/cancel the merge request. If I'm able to demonstrate then I'll open a new merge request and include the test case. Thanks again.

**Pull request closed without merging**
